[package]
name = "axum-otel-metrics"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "axum middleware for intergrate OpenTelemetry metrics and export to Prometheus"
homepage = "https://ttys3.dev/"
repository = "https://github.com/ttys3/axum-otel-metrics/"
documentation = "https://docs.rs/axum-otel-metrics"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum = { version = "0.6.0-rc.2", features = ["headers"] }
tokio = { version = "1.21.2", features = ["full", "tracing"] }
opentelemetry = { version = "0.18.0", features = ["metrics", "rt-tokio"] }
opentelemetry-prometheus = { version = "0.11.0", features = ["prometheus-encoding"] }
prometheus = "0.13.2"
tracing = "0.1.37"
tower = "0.4.13"
futures-util = "0.3.24"
pin-project-lite = "0.2.9"
rand = "0.8.5"
