[package]
name = "axum-metrics-demo"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum-otel-metrics = { path = "../../" }
axum = { version = "0.6.0-rc.2" }
tokio = { version = "1.21.2", features = ["full", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8.5"
